chore: Add check for iso
Signed-off-by: Zeglius <33781398+Zeglius@users.noreply.github.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -61,3 +61,11 @@ runs:
         cd "${{ github.action_path }}"
         # Cleanup
         sudo PATH="$PATH" $(which just) clean
+        
+    - name: Check the iso is there
+      shell: bash
+      run: |
+        [[ -f $dest ]] || {
+          echo "::error:Iso file does not exist at $dest"
+          exit 1
+        }
